package com.nairbspace.octoandroid.data.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nairbspace.octoandroid.data.db.Printer;

import com.nairbspace.octoandroid.data.db.PrinterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig printerDaoConfig;

    private final PrinterDao printerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        printerDaoConfig = daoConfigMap.get(PrinterDao.class).clone();
        printerDaoConfig.initIdentityScope(type);

        printerDao = new PrinterDao(printerDaoConfig, this);

        registerDao(Printer.class, printerDao);
    }
    
    public void clear() {
        printerDaoConfig.getIdentityScope().clear();
    }

    public PrinterDao getPrinterDao() {
        return printerDao;
    }

}
