package com.nairbspace.octoandroid.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nairbspace.octoandroid.model.Printer;
import com.nairbspace.octoandroid.model.Version;

import com.nairbspace.octoandroid.model.PrinterDao;
import com.nairbspace.octoandroid.model.VersionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig printerDaoConfig;
    private final DaoConfig versionDaoConfig;

    private final PrinterDao printerDao;
    private final VersionDao versionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        printerDaoConfig = daoConfigMap.get(PrinterDao.class).clone();
        printerDaoConfig.initIdentityScope(type);

        versionDaoConfig = daoConfigMap.get(VersionDao.class).clone();
        versionDaoConfig.initIdentityScope(type);

        printerDao = new PrinterDao(printerDaoConfig, this);
        versionDao = new VersionDao(versionDaoConfig, this);

        registerDao(Printer.class, printerDao);
        registerDao(Version.class, versionDao);
    }
    
    public void clear() {
        printerDaoConfig.getIdentityScope().clear();
        versionDaoConfig.getIdentityScope().clear();
    }

    public PrinterDao getPrinterDao() {
        return printerDao;
    }

    public VersionDao getVersionDao() {
        return versionDao;
    }

}
