package com.nairbspace.octoandroid.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VERSION".
 */
public class Version {

    private Long id;
    /** Not-null value. */
    private String api;
    /** Not-null value. */
    private String server;

    public Version() {
    }

    public Version(Long id) {
        this.id = id;
    }

    public Version(Long id, String api, String server) {
        this.id = id;
        this.api = api;
        this.server = server;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getApi() {
        return api;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApi(String api) {
        this.api = api;
    }

    /** Not-null value. */
    public String getServer() {
        return server;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setServer(String server) {
        this.server = server;
    }

}
