package com.nairbspace.octoandroid.data.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nairbspace.octoandroid.data.db.PrinterDbEntity;

import com.nairbspace.octoandroid.data.db.PrinterDbEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig printerDbEntityDaoConfig;

    private final PrinterDbEntityDao printerDbEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        printerDbEntityDaoConfig = daoConfigMap.get(PrinterDbEntityDao.class).clone();
        printerDbEntityDaoConfig.initIdentityScope(type);

        printerDbEntityDao = new PrinterDbEntityDao(printerDbEntityDaoConfig, this);

        registerDao(PrinterDbEntity.class, printerDbEntityDao);
    }
    
    public void clear() {
        printerDbEntityDaoConfig.getIdentityScope().clear();
    }

    public PrinterDbEntityDao getPrinterDbEntityDao() {
        return printerDbEntityDao;
    }

}
