package com.nairbspace.octoandroid.data.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRINTER".
 */
public class Printer {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String api_key;
    /** Not-null value. */
    private String scheme;
    /** Not-null value. */
    private String host;
    private int port;
    /** Not-null value. */
    private String version_json;
    /** Not-null value. */
    private String connection_json;

    public Printer() {
    }

    public Printer(Long id) {
        this.id = id;
    }

    public Printer(Long id, String name, String api_key, String scheme, String host, int port, String version_json, String connection_json) {
        this.id = id;
        this.name = name;
        this.api_key = api_key;
        this.scheme = scheme;
        this.host = host;
        this.port = port;
        this.version_json = version_json;
        this.connection_json = connection_json;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getApi_key() {
        return api_key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApi_key(String api_key) {
        this.api_key = api_key;
    }

    /** Not-null value. */
    public String getScheme() {
        return scheme;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    /** Not-null value. */
    public String getHost() {
        return host;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHost(String host) {
        this.host = host;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    /** Not-null value. */
    public String getVersion_json() {
        return version_json;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVersion_json(String version_json) {
        this.version_json = version_json;
    }

    /** Not-null value. */
    public String getConnection_json() {
        return connection_json;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setConnection_json(String connection_json) {
        this.connection_json = connection_json;
    }

}
